# Generated by Django 3.1.5 on 2021-01-15 05:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 15, 5, 32, 48, 683134, tzinfo=utc)),
        ),
    ]
