# Generated by Django 3.1.5 on 2021-01-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210114_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='due_date',
            field=models.DateField(default='2021-01-15'),
        ),
    ]
